services:
  - type: web
    name: yt-live-stream
    env: python
    plan: free
    buildCommand: |
      apt update && apt install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python stream.py
    envVars:
      - key: STREAM_KEY
        generateValue: secret
      - key: INPUT_FILE
        value: video.mp4
